- hosts: db_server
  become: yes
  gather_subset: network
  vars_files:
    - host_vars/remote_vars.yaml
  roles:
    - role: couchdb


# - hosts: all
#   become: yes
#   gather_facts: no
#   vars_files:
#     - host_vars/remote_vars.yaml
#   roles:
#     - role: remote-user-timeline
